### ISSUE TITLE
We have several Bendix G-15s, peripherals, paper tapes, docs, mag tapes etc

### ISSUE THREAD

**Issue by broswell** [pkimpel/retro-g15#1]
Hello -
We recently acquired (https://museum.syssrc.com) a few tons of Bendix G-15 related items.  Today's project is to make a modern paper tape reader work.  Looking forward to using recovered software on your emulator.  Project site at http://www.phkimpel.us/Bendix-G15/ is down for me.

Bob

**Comment by pkimpel** [comment]
Wow, Bob -- this is amazing. Thanks very much for writing and
      letting me know.
    Sorry about the bad link. It's now fixed, but that site is in a
      very preliminary state. There's not much there, and what there is
      doesn't do much yet. The only thing remotely interesting at this
      point is to follow the link for the emulator
        home page and click the Start the Emulator button. That will
      open an overlay over the home page and display the current
      rendition of the G-15's control panel, paper-tape units (at the
      top), and typewriter output (at the bottom). Nothing works there
      yet, but you can at least admire the layout. Click the OFF button
      to get back to the home page.
    I've never used a G-15, although I've seen one in a
      decommissioned state. I've been interested in emulating it for
      years, have been studying it in detail for past several months,
      and just started on the emulator design in November. It's been
      slow going, and I've now had to set it aside until mid-February
      due to other obligations. It is a very strange architecture,
      taking many ideas from the Pilot ACE, but using a drum rather than
      mercury delay lines for its memory. I've never seen a more
      difficult architecture to program. It doesn't even have op codes!
      It's proving to be a real challenge to emulate, and I confess that
      my interest has been flagging somewhat, especially since thus far
      I've been able to find so little software for it.
    Your email, and the promise of significant additional software,
      has improved my outlook considerably. I'll be very interested in
      learning more about your acquisitions and what items, particularly
      software, you now have.
    One of the problems with emulating the G-15 is that there are a
      number of picky restrictions on the way instructions must be coded
      (e.g., words having to start on odd or even addresses), but very
      little information on what should happen if those restrictions are
      violated. In principle, you could determine that from the
      schematics, but understanding schematics is not one of my strong
      suits -- I'm just a software guy. My current goal is to produce an
      emulator that runs at real G-15 speed and functions correctly as
      long as the software follows the published rules. One thing that
      we know about programmers in the 1950s and early -60s, though, is
      that they often didn't follow the rules and took advantage of
      undocumented quirks in the hardware. It will be interesting to see
      how much of that we encounter.
    Up to now I was planning to implement only a basic G-15 --
      processor, memory, typewriter, and in-cabinet paper tape reader
      and punch -- mostly because I haven't had access to software that
      used anything else. Once I have that basic configuration working,
      I'm certainly interested in implementing additional peripherals if
      there will be software to support them.
    Much of what I have has come either from bitsavers.org
      or David Green's G-15 web site in
      Australia. I understand that David worked on a G-15 emulator ten
      or so years ago, but hasn't made it public, and I don't think it's
      finished. I haven't found evidence that anyone else has been
      interested enough (or perhaps brave enough) to build an emulator
      for the system.
    
    I'll get back to development of my emulator next month, now with
      renewed interest. I'll keep posted on my progress. My email
      address is ***@***.*** Thanks again for contacting me.
    
    Paul Kimpel
San Diego, California
(mobile) +1-619-917-3756
    -------- Original Message --------
      Subject: [pkimpel/retro-g15] We have several Bendix G-15s,
      peripherals, paper tapes, docs, mag tapes etc (Issue Bob Roswell)
      From: Bob Roswell ***@***.***>
      To: pkimpel/retro-g15 ***@***.***>
      Cc: Subscribed ***@***.***>
      Date: Sun Jan 16 2022 07:03:41 GMT-0800 (Pacific Standard
      Time)
    
    
      
      Hello -
        We recently acquired (https://museum.syssrc.com) a
        few tons of Bendix G-15 related items. Today's project is to
        make a modern paper tape reader work. Looking forward to using
        recovered software on your emulator. Project site at http://www.phkimpel.us/Bendix-G15/
        is down for me.
      Bob
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you are subscribed to this
        thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pkimpel/retro-g15/issues/1",
"url": "https://github.com/pkimpel/retro-g15/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by broswell** [comment]
I had fun learning how to use GitHub!

From: Paul Kimpel ***@***.***>
Sent: Sunday, January 16, 2022 8:04 PM
To: pkimpel/retro-g15 ***@***.***>
Cc: Bob Roswell ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [pkimpel/retro-g15] We have several Bendix G-15s, peripherals, paper tapes, docs, mag tapes etc (Issue #1)


Closed #1<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pkimpel_retro-2Dg15_issues_1&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=IdFC6KVjMh11poEAtOxdlSfBzRH90l3lbPvEjfJS1FE&m=5Qwk-0grzK5OVqnxZFuN6l6WBJ_JlLUA6WilyZkhIr8&s=E1-3wFlr_nJ9vNLplKd29Iw-bl0ViO9kxio-7GucE6I&e=>.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pkimpel_retro-2Dg15_issues_1-23event-2D5901111814&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=IdFC6KVjMh11poEAtOxdlSfBzRH90l3lbPvEjfJS1FE&m=5Qwk-0grzK5OVqnxZFuN6l6WBJ_JlLUA6WilyZkhIr8&s=7_xkWG2TMzuePEYcWp6JNvTpxRa2ViZH3cG7PWDcnrM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABORPT2KWL6DJWIVAR6RW3LUWNTHHANCNFSM5MC3SSGA&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=IdFC6KVjMh11poEAtOxdlSfBzRH90l3lbPvEjfJS1FE&m=5Qwk-0grzK5OVqnxZFuN6l6WBJ_JlLUA6WilyZkhIr8&s=PnmPP2c1MG6D_1aTA6uiAnLwFD6tnzkekTOjUFtN4wo&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=IdFC6KVjMh11poEAtOxdlSfBzRH90l3lbPvEjfJS1FE&m=5Qwk-0grzK5OVqnxZFuN6l6WBJ_JlLUA6WilyZkhIr8&s=OGiIQSd9jIYqLsEr68gcVUNtwfHoiI4X8HkJO91OKmg&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=IdFC6KVjMh11poEAtOxdlSfBzRH90l3lbPvEjfJS1FE&m=5Qwk-0grzK5OVqnxZFuN6l6WBJ_JlLUA6WilyZkhIr8&s=SEj8SZcw-zxeACQV2rOSsnD4UveCtdXJIGD6Flp_MvM&e=>.
